# Generated by Django 5.2.10 on 2026-01-14 06:26

from django.db import migrations


def create_groups_and_superuser(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")

    # Groups to create
    group_names = [
        "admin",  # original admin group
        "admin_p3de",
        "admin_pide",
        "admin_pmde",
        "kasi_p3de",
        "kasi_pide",
        "user_p3de",
        "user_pide",
        "user_pmde",
    ]

    for name in group_names:
        Group.objects.get_or_create(name=name)

    # Create admin superuser if not exists (credentials from previous migration)
    if not User.objects.filter(username="admin").exists():
        User.objects.create_superuser("admin", "admin@diamond.pde", "admin")


def delete_groups_and_superuser(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")

    group_names = [
        "admin",
        "admin_p3de",
        "admin_pide",
        "admin_pmde",
        "kasi_p3de",
        "kasi_pide",
        "user_p3de",
        "user_pide",
        "user_pmde",
    ]

    Group.objects.filter(name__in=group_names).delete()
    User.objects.filter(username="admin").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("diamond_web", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups_and_superuser, reverse_code=delete_groups_and_superuser),
    ]
