# Generated by Django 5.2.10 on 2026-01-14 07:45

from django.db import migrations


def create_superuser_and_admin_group(apps, schema_editor):
    """
    Creates a superuser 'admin' with password 'admin' and an 'Admin' group.
    Adds the superuser to the 'Admin' group.
    """
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")

    # Create Admin group, or get it if it already exists
    admin_group, created = Group.objects.get_or_create(name="Admin")

    # Create superuser if it doesn't exist
    if not User.objects.filter(username="admin").exists():
        superuser = User.objects.create_superuser("admin", "admin@diamond.pde", "admin")
        superuser.groups.add(admin_group)


class Migration(migrations.Migration):
    dependencies = [
        ("diamond_web", "0002_kategoriilap"),
    ]

    operations = [
        migrations.RunPython(create_superuser_and_admin_group),
    ]