# Generated by Django 5.2.10 on 2026-01-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0004_seed_kategori_ilap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoriilap',
            options={'ordering': ['id_kategori'], 'verbose_name': 'Kategori ILAP', 'verbose_name_plural': 'Kategori ILAP'},
        ),
    ]
