# Generated by Django 5.2.14 on 2026-06-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0004_seed_tiket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiket',
            name='nomor_surat_pengantar',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nomor Surat Pengantar'),
        ),
    ]
