# Generated by Django 5.2.10 on 2026-01-14 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0005_alter_kategoriilap_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ILAP',
            fields=[
                ('id_ilap', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='ID ILAP')),
                ('nama_ilap', models.CharField(max_length=150, verbose_name='Nama ILAP')),
                ('id_kategori', models.ForeignKey(db_column='id_kategori', on_delete=django.db.models.deletion.CASCADE, to='diamond_web.kategoriilap', verbose_name='ID Kategori')),
            ],
            options={
                'verbose_name': 'ILAP',
                'verbose_name_plural': 'ILAP',
                'db_table': 'ilap',
                'ordering': ['id_ilap'],
            },
        ),
    ]
