# Generated by Django 5.2.14 on 2026-07-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0006_sequencetandaterima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodepengiriman',
            name='periode_penyampaian',
            field=models.CharField(max_length=50, verbose_name='Periode Penyampaian'),
        ),
        migrations.AlterUniqueTogether(
            name='periodepengiriman',
            unique_together={('periode_penyampaian', 'periode_penerimaan')},
        ),
    ]
