# Generated by Django 5.2.10 on 2026-01-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0006_seed_kategori_wilayah'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlasifikasiTabel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=50, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name': 'Klasifikasi Tabel',
                'verbose_name_plural': 'Klasifikasi Tabel',
                'db_table': 'klasifikasi_tabel',
                'ordering': ['id'],
            },
        ),
    ]
