# Generated by Django 5.2.14 on 2026-07-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0007_remove_ilap_id_kpp_create_ilapkpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiket',
            name='special_request',
            field=models.BooleanField(default=False, verbose_name='Special Request'),
        ),
    ]
