# Generated by Django 5.2.14 on 2026-07-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamond_web", "0010_seed_ilap_kanwil_mapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiket",
            name="alasan_ketidaktersediaan",
            field=models.TextField(
                blank=True, null=True, verbose_name="Alasan Ketidaktersediaan"
            ),
        ),
    ]
