# Generated by Django 5.2.14 on 2026-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamond_web", "0011_alter_tiket_alasan_ketidaktersediaan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiket",
            name="alasan_ketidaktersediaan",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Alasan Ketidaktersediaan",
            ),
        ),
    ]
