# Generated by Django 5.2.14 on 2026-08-04 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diamond_web", "0011_tiket_tgl_special_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStarredTiket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nomor_tiket",
                    models.CharField(max_length=17, verbose_name="Nomor Tiket"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_user",
                    models.ForeignKey(
                        db_column="id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Starred Tiket",
                "verbose_name_plural": "User Starred Tikets",
                "db_table": "user_starred_tiket",
                "ordering": ["-created_at"],
                "unique_together": {("id_user", "nomor_tiket")},
            },
        ),
    ]
