# Generated by Django 5.2.10 on 2026-01-29 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diamond_web", "0012_seed_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tiket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nomor_tiket",
                    models.CharField(
                        blank=True, max_length=17, null=True, verbose_name="Nomor Tiket"
                    ),
                ),
                (
                    "periode",
                    models.IntegerField(blank=True, null=True, verbose_name="Periode"),
                ),
                (
                    "tahun",
                    models.IntegerField(blank=True, null=True, verbose_name="Tahun"),
                ),
                (
                    "status",
                    models.IntegerField(blank=True, null=True, verbose_name="Status"),
                ),
                (
                    "tgl_terima_vertikal",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Terima Vertikal"
                    ),
                ),
                (
                    "tgl_terima_dip",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Terima DIP"
                    ),
                ),
                (
                    "tgl_teliti",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Teliti"
                    ),
                ),
                (
                    "baris_p3de",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Baris P3DE"
                    ),
                ),
                (
                    "tgl_nadine",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Nadine"
                    ),
                ),
                (
                    "tgl_kirim_pide",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Kirim PIDE"
                    ),
                ),
                (
                    "tgl_dibatalkan",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Dibatalkan"
                    ),
                ),
                (
                    "tgl_dikembalikan",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Dikembalikan"
                    ),
                ),
                (
                    "baris_i",
                    models.IntegerField(blank=True, null=True, verbose_name="Baris I"),
                ),
                (
                    "baris_u",
                    models.IntegerField(blank=True, null=True, verbose_name="Baris U"),
                ),
                (
                    "baris_res",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Baris Res"
                    ),
                ),
                (
                    "baris_cde",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Baris CDE"
                    ),
                ),
                (
                    "tgl_transfer",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Transfer"
                    ),
                ),
                (
                    "tgl_rematch",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Rematch"
                    ),
                ),
                (
                    "sudah_qc",
                    models.IntegerField(blank=True, null=True, verbose_name="Sudah QC"),
                ),
                (
                    "belum_qc",
                    models.IntegerField(blank=True, null=True, verbose_name="Belum QC"),
                ),
                (
                    "lolos_qc",
                    models.IntegerField(blank=True, null=True, verbose_name="Lolos QC"),
                ),
                (
                    "tidak_lolos_qc",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tidak Lolos QC"
                    ),
                ),
                (
                    "qc_c",
                    models.IntegerField(blank=True, null=True, verbose_name="QC C"),
                ),
                (
                    "id_periode_data",
                    models.ForeignKey(
                        db_column="id_periode_data",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diamond_web.periodejenisdata",
                        verbose_name="Periode Jenis Data",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tiket",
                "verbose_name_plural": "Tiket",
                "db_table": "tiket",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TiketAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Timestamp"
                    ),
                ),
                (
                    "action",
                    models.IntegerField(blank=True, null=True, verbose_name="Action"),
                ),
                (
                    "catatan",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Catatan"
                    ),
                ),
                (
                    "id_tiket",
                    models.ForeignKey(
                        db_column="id_tiket",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diamond_web.tiket",
                        verbose_name="Tiket",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        db_column="id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tiket Action",
                "verbose_name_plural": "Tiket Actions",
                "db_table": "tiket_action",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TiketPIC",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Timestamp"
                    ),
                ),
                (
                    "role",
                    models.IntegerField(blank=True, null=True, verbose_name="Role"),
                ),
                (
                    "id_tiket",
                    models.ForeignKey(
                        db_column="id_tiket",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diamond_web.tiket",
                        verbose_name="Tiket",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        db_column="id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tiket PIC",
                "verbose_name_plural": "Tiket PICs",
                "db_table": "tiket_pic",
                "ordering": ["id"],
            },
        ),
    ]
