# Generated by Django 5.2.14 on 2026-08-12 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('diamond_web', '0012_userstarredtiket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='durasijatuhtempo',
            index=models.Index(fields=['id_sub_jenis_data', 'seksi', '-start_date'], name='djt_sub_seksi_start_idx'),
        ),
        migrations.AddIndex(
            model_name='jenisprioritasdata',
            index=models.Index(fields=['id_sub_jenis_data_ilap', 'start_date', 'end_date'], name='jpd_sub_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='pic',
            index=models.Index(condition=models.Q(('end_date__isnull', True)), fields=['tipe', 'id_sub_jenis_data_ilap'], name='pic_aktif_tipe_sub_idx'),
        ),
        migrations.AddIndex(
            model_name='tiket',
            index=models.Index(fields=['status_tiket'], name='tiket_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tiketaction',
            index=models.Index(fields=['id_tiket', 'action'], name='taction_tiket_act_idx'),
        ),
        migrations.AddIndex(
            model_name='tiketpic',
            index=models.Index(condition=models.Q(('active', True)), fields=['id_user', 'role'], name='tpic_user_role_act_idx'),
        ),
        migrations.AddIndex(
            model_name='tiketpic',
            index=models.Index(condition=models.Q(('active', True)), fields=['id_tiket', 'role'], name='tpic_tiket_role_act_idx'),
        ),
    ]
