# Generated by Django 5.2.10 on 2026-01-29 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diamond_web", "0013_tiket_tiketaction_tiketpic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TandaTerimaData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nomor_tanda_terima",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nomor Tanda Terima"
                    ),
                ),
                (
                    "tanggal_tanda_terima",
                    models.DateTimeField(verbose_name="Tanggal Tanda Terima"),
                ),
                (
                    "deskripsi",
                    models.CharField(max_length=255, verbose_name="Deskripsi"),
                ),
                (
                    "id_ilap",
                    models.ForeignKey(
                        db_column="id_ilap",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diamond_web.ilap",
                        verbose_name="ILAP",
                    ),
                ),
                (
                    "id_perekam",
                    models.ForeignKey(
                        db_column="id_perekam",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Perekam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tanda Terima Data",
                "verbose_name_plural": "Tanda Terima Data",
                "db_table": "tanda_terima_data",
                "ordering": ["-tanggal_tanda_terima"],
            },
        ),
    ]
