# Generated by Django 5.2.14 on 2026-09-04 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('diamond_web', '0014_kasubdit_pde_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AturanDurasiJatuhTempo',
            fields=[
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Create Date')),
                ('create_by', models.CharField(blank=True, max_length=9, null=True, verbose_name='Create By')),
                ('update_date', models.DateField(blank=True, null=True, verbose_name='Update Date')),
                ('update_by', models.CharField(blank=True, max_length=9, null=True, verbose_name='Update By')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(verbose_name='Tahun')),
                ('durasi_prioritas', models.IntegerField(help_text='Hari jatuh tempo bila data berstatus prioritas pada tahun itu.', verbose_name='Durasi Prioritas')),
                ('durasi_non_prioritas', models.IntegerField(help_text='Hari jatuh tempo bila data tidak berstatus prioritas.', verbose_name='Durasi Non Prioritas')),
                ('id_ilap', models.ForeignKey(blank=True, db_column='id_ilap', help_text='Kosongkan untuk aturan umum. Diisi bila satu ILAP punya durasi sendiri.', null=True, on_delete=django.db.models.deletion.PROTECT, to='diamond_web.ilap', verbose_name='ILAP')),
                ('id_sub_jenis_data', models.ForeignKey(blank=True, db_column='id_sub_jenis_data', help_text='Kosongkan kecuali satu sub jenis data perlu durasi berbeda dari ILAP-nya.', null=True, on_delete=django.db.models.deletion.PROTECT, to='diamond_web.jenisdatailap', verbose_name='Sub Jenis Data ILAP')),
                ('seksi', models.ForeignKey(db_column='seksi', help_text='Grup seksi pemilik aturan, mis. user_pide atau user_pmde.', on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Seksi')),
            ],
            options={
                'verbose_name': 'Aturan Durasi Jatuh Tempo',
                'verbose_name_plural': 'Aturan Durasi Jatuh Tempo',
                'db_table': 'aturan_durasi_jatuh_tempo',
                'ordering': ['seksi', 'tahun', 'id_ilap', 'id_sub_jenis_data'],
                'indexes': [models.Index(fields=['seksi', 'tahun'], name='adjt_seksi_tahun_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('id_ilap__isnull', True), ('id_sub_jenis_data__isnull', True)), fields=('seksi', 'tahun'), name='unique_aturan_durasi_umum'), models.UniqueConstraint(condition=models.Q(('id_ilap__isnull', False), ('id_sub_jenis_data__isnull', True)), fields=('seksi', 'tahun', 'id_ilap'), name='unique_aturan_durasi_ilap'), models.UniqueConstraint(condition=models.Q(('id_sub_jenis_data__isnull', False)), fields=('seksi', 'tahun', 'id_sub_jenis_data'), name='unique_aturan_durasi_sub_jenis')],
            },
        ),
    ]
