# Generated by Django 5.2.14 on 2026-09-23 09:50

from django.core.files.base import ContentFile
from django.db import migrations, models


def copy_nd_pengantar_pide_template(apps, schema_editor):
    """Start ND Pengantar ke PDI off as a copy of the P3DE ND Pengantar.

    PMDE has no letter of its own yet, so it borrows the one P3DE sends to
    PIDE. The file copied is whichever ND Pengantar PIDE template is active
    in this database — the one P3DE actually uses here, which may well be a
    later upload than the fixture — so the two can then drift apart
    independently. Without such a template (a fresh install, before
    ``load_default_templates``) nothing is created; that command seeds the PDI
    template from its own fixture instead.
    """
    DocxTemplate = apps.get_model('diamond_web', 'DocxTemplate')
    if DocxTemplate.objects.filter(jenis_dokumen='nd_pengantar_pdi').exists():
        return
    source = (
        DocxTemplate.objects.filter(jenis_dokumen='nd_pengantar_pide', active=True)
        .exclude(file_template='')
        .order_by('-updated_at')
        .first()
    )
    if source is None:
        return
    try:
        with source.file_template.open('rb') as fh:
            content = fh.read()
    except (FileNotFoundError, OSError):
        return
    copy = DocxTemplate(
        nama_template='ND Pengantar ke PDI',
        deskripsi='Naskah Dinas pengantar data adhoc ke PDI (sementara salinan ND Pengantar ke PIDE)',
        jenis_dokumen='nd_pengantar_pdi',
        active=True,
    )
    copy.file_template.save('nd_pengantar_pdi.docx', ContentFile(content), save=True)


def remove_nd_pengantar_pdi_template(apps, schema_editor):
    DocxTemplate = apps.get_model('diamond_web', 'DocxTemplate')
    for template in DocxTemplate.objects.filter(jenis_dokumen='nd_pengantar_pdi'):
        if template.file_template:
            template.file_template.delete(save=False)
        template.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0016_seed_aturan_durasi_jatuh_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docxtemplate',
            name='jenis_dokumen',
            field=models.CharField(choices=[('tanda_terima_nasional_internasional', 'Tanda Terima ILAP Nasional/Internasional'), ('tanda_terima_regional', 'Tanda Terima ILAP Regional'), ('lampiran_tanda_terima_nasional_internasional', 'Lampiran Tanda Terima ILAP Nasional/Internasional'), ('lampiran_tanda_terima_regional', 'Lampiran Tanda Terima ILAP Regional'), ('register_penerimaan_data', 'Register Penerimaan Data'), ('nd_pengantar_pide', 'ND Pengantar ke PIDE'), ('nd_pengantar_pdi', 'ND Pengantar ke PDI'), ('surat_klarifikasi', 'Surat Klarifikasi'), ('surat_pkdi_nasional_internasional_lengkap', 'Surat PKDI ILAP Nasional/Internasional Lengkap'), ('surat_pkdi_nasional_internasional_sebagian', 'Surat PKDI ILAP Nasional/Internasional Lengkap Sebagian'), ('surat_pkdi_regional_lengkap', 'Surat PKDI ILAP Regional Lengkap'), ('surat_pkdi_regional_sebagian', 'Surat PKDI ILAP Regional Lengkap Sebagian')], help_text='Jenis dokumen yang akan dihasilkan', max_length=50),
        ),
        migrations.RunPython(
            copy_nd_pengantar_pide_template,
            reverse_code=remove_nd_pengantar_pdi_template,
        ),
    ]
