# Generated by Django 5.2.10 on 2026-02-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0017_backupdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupdata',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='backupdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='backupdata',
            name='updated_at',
        ),
    ]
