# Generated by Django 5.2.17 on 2026-10-07 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0017_nd_pengantar_pdi_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiketKdTahap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_tahap', models.CharField(blank=True, max_length=50, null=True, verbose_name='KD Tahap')),
                ('jumlah_baris', models.IntegerField(verbose_name='Jumlah Baris')),
                ('id_tiket', models.ForeignKey(db_column='id_tiket', on_delete=django.db.models.deletion.CASCADE, related_name='kd_tahap_set', to='diamond_web.tiket', verbose_name='Tiket')),
            ],
            options={
                'verbose_name': 'Tiket KD Tahap',
                'verbose_name_plural': 'Tiket KD Tahap',
                'db_table': 'tiket_kd_tahap',
                'ordering': ['id_tiket', 'kd_tahap'],
                'constraints': [models.UniqueConstraint(fields=('id_tiket', 'kd_tahap'), name='tiket_kd_tahap_uniq')],
            },
        ),
    ]
