# Generated by Django 5.2.17 on 2026-10-08 08:16

from django.db import migrations, models


def hapus_baris_tanpa_qc(apps, schema_editor):
    # Rows from before this migration count every QC value of a KD Tahap
    # together; left with qc = NULL they would read as "belum QC". They are
    # refilled per QC by `manage.py sync_tiket_kd_tahap --tahun <tahun>`.
    apps.get_model('diamond_web', 'TiketKdTahap').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0018_tiket_kd_tahap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiketkdtahap',
            options={'ordering': ['id_tiket', 'kd_tahap', 'qc'], 'verbose_name': 'Tiket KD Tahap', 'verbose_name_plural': 'Tiket KD Tahap'},
        ),
        migrations.RemoveConstraint(
            model_name='tiketkdtahap',
            name='tiket_kd_tahap_uniq',
        ),
        migrations.AddField(
            model_name='tiketkdtahap',
            name='qc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='QC'),
        ),
        migrations.AddConstraint(
            model_name='tiketkdtahap',
            constraint=models.UniqueConstraint(fields=('id_tiket', 'kd_tahap', 'qc'), name='tiket_kd_tahap_qc_uniq'),
        ),
        migrations.RunPython(hapus_baris_tanpa_qc, migrations.RunPython.noop),
    ]
