# Generated by Django 5.2.17 on 2026-10-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0018_p3der_groups'),
        ('diamond_web', '0019_tiket_kd_tahap_qc'),
    ]

    operations = [
    ]
