# Generated by Django 5.2.17 on 2026-10-08 15:54

#
# Seksi P3DE and Seksi P3DER number their tanda terima in separate series:
# P3DE as ...TTD/PJ.1031/..., P3DER as ...TTD/PJ.1032/.... Both tables gain a
# `seksi` column and uniqueness becomes per seksi. Every existing row was
# issued as PJ.1031, so the default ('P3DE') is exactly what they get.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0020_merge_0018_p3der_groups_0019_tiket_kd_tahap_qc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sequencetandaterima',
            options={'ordering': ['-tahun', 'seksi'], 'verbose_name': 'Sequence Tanda Terima', 'verbose_name_plural': 'Sequence Tanda Terima'},
        ),
        migrations.AlterUniqueTogether(
            name='tandaterimadata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sequencetandaterima',
            name='seksi',
            field=models.CharField(choices=[('P3DE', 'P3DE (PJ.1031)'), ('P3DER', 'P3DER (PJ.1032)')], default='P3DE', help_text='Seksi pemilik seri nomor tanda terima', max_length=5, verbose_name='Seksi'),
        ),
        migrations.AddField(
            model_name='tandaterimadata',
            name='seksi',
            field=models.CharField(choices=[('P3DE', 'P3DE (PJ.1031)'), ('P3DER', 'P3DER (PJ.1032)')], default='P3DE', max_length=5, verbose_name='Seksi'),
        ),
        migrations.AlterField(
            model_name='sequencetandaterima',
            name='tahun',
            field=models.IntegerField(help_text='Tahun penerapan sequence', verbose_name='Tahun'),
        ),
        migrations.AlterUniqueTogether(
            name='tandaterimadata',
            unique_together={('seksi', 'nomor_tanda_terima', 'tahun_terima')},
        ),
        migrations.AddConstraint(
            model_name='sequencetandaterima',
            constraint=models.UniqueConstraint(fields=('seksi', 'tahun'), name='seq_tt_seksi_tahun_uniq'),
        ),
    ]
