# Generated by Django 5.2.10 on 2026-02-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0024_tiketpic_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiketpic',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'P3DE'), (2, 'PIDE'), (3, 'PMDE')], null=True, verbose_name='Role'),
        ),
    ]
