# Generated by Django 5.2.10 on 2026-02-07 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0025_alter_tiketpic_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detiltandaterima',
            name='id_tiket',
            field=models.ForeignKey(db_column='id_tiket', on_delete=django.db.models.deletion.CASCADE, to='diamond_web.tiket', verbose_name='Tiket'),
        ),
    ]
