# Generated by Django 5.2.10 on 2026-02-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0022_tiket_status_refactor'),
        ('diamond_web', '0026_remove_unique_id_tiket'),
    ]

    operations = [
    ]
