# Generated by Django 5.2.10 on 2026-02-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0027_merge_20260208_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilap',
            name='nama_ilap',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nama ILAP'),
        ),
        migrations.AddConstraint(
            model_name='jenisprioritasdata',
            constraint=models.UniqueConstraint(fields=('id_sub_jenis_data_ilap', 'tahun'), name='unique_subjenis_tahun'),
        ),
    ]
