# Generated by Django 5.2.10 on 2026-02-11 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('diamond_web', '0028_alter_ilap_nama_ilap_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupdata',
            name='id_tiket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backups', to='diamond_web.tiket', verbose_name='No Tiket'),
        ),
        migrations.AlterField(
            model_name='detiltandaterima',
            name='id_tanda_terima',
            field=models.ForeignKey(db_column='id_tanda_terima', on_delete=django.db.models.deletion.PROTECT, related_name='detil_items', to='diamond_web.tandaterimadata', verbose_name='Tanda Terima Data'),
        ),
        migrations.AlterField(
            model_name='detiltandaterima',
            name='id_tiket',
            field=models.ForeignKey(db_column='id_tiket', on_delete=django.db.models.deletion.PROTECT, to='diamond_web.tiket', verbose_name='Tiket'),
        ),
        migrations.AlterField(
            model_name='durasijatuhtempo',
            name='id_sub_jenis_data',
            field=models.ForeignKey(db_column='id_sub_jenis_data', on_delete=django.db.models.deletion.PROTECT, to='diamond_web.jenisdatailap', verbose_name='Sub Jenis Data ILAP'),
        ),
        migrations.AlterField(
            model_name='durasijatuhtempo',
            name='seksi',
            field=models.ForeignKey(db_column='seksi', on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Seksi'),
        ),
        migrations.AlterField(
            model_name='ilap',
            name='id_kategori',
            field=models.ForeignKey(db_column='id_kategori', on_delete=django.db.models.deletion.PROTECT, to='diamond_web.kategoriilap', verbose_name='ID Kategori'),
        ),
        migrations.AlterField(
            model_name='ilap',
            name='id_kategori_wilayah',
            field=models.ForeignKey(db_column='id_kategori_wilayah', on_delete=django.db.models.deletion.PROTECT, to='diamond_web.kategoriwilayah', verbose_name='Kategori Wilayah'),
        ),
        migrations.AlterField(
            model_name='jenisdatailap',
            name='id_ilap',
            field=models.ForeignKey(db_column='id_ilap', on_delete=django.db.models.deletion.PROTECT, to='diamond_web.ilap', verbose_name='ILAP'),
        ),
        migrations.AlterField(
            model_name='jenisdatailap',
            name='id_jenis_tabel',
            field=models.ForeignKey(db_column='id_jenis_tabel', on_delete=django.db.models.deletion.PROTECT, to='diamond_web.jenistabel', verbose_name='Jenis Tabel'),
        ),
        migrations.AlterField(
            model_name='jenisprioritasdata',
            name='id_sub_jenis_data_ilap',
            field=models.ForeignKey(db_column='id_sub_jenis_data_ilap', on_delete=django.db.models.deletion.PROTECT, to='diamond_web.jenisdatailap', verbose_name='Sub Jenis Data ILAP'),
        ),
        migrations.AlterField(
            model_name='klasifikasijenisdata',
            name='id_jenis_data_ilap',
            field=models.ForeignKey(db_column='id_jenis_data_ilap', on_delete=django.db.models.deletion.PROTECT, to='diamond_web.jenisdatailap', verbose_name='Jenis Data ILAP'),
        ),
        migrations.AlterField(
            model_name='klasifikasijenisdata',
            name='id_klasifikasi_tabel',
            field=models.ForeignKey(db_column='id_klasifikasi_tabel', on_delete=django.db.models.deletion.PROTECT, to='diamond_web.klasifikasitabel', verbose_name='Klasifikasi Tabel'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='periodejenisdata',
            name='id_periode_pengiriman',
            field=models.ForeignKey(db_column='id_periode_pengiriman', on_delete=django.db.models.deletion.PROTECT, to='diamond_web.periodepengiriman', verbose_name='Periode Pengiriman'),
        ),
        migrations.AlterField(
            model_name='periodejenisdata',
            name='id_sub_jenis_data_ilap',
            field=models.ForeignKey(db_column='id_sub_jenis_data_ilap', on_delete=django.db.models.deletion.PROTECT, to='diamond_web.jenisdatailap', verbose_name='Sub Jenis Data ILAP'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='id_sub_jenis_data_ilap',
            field=models.ForeignKey(db_column='id_sub_jenis_data_ilap', on_delete=django.db.models.deletion.PROTECT, to='diamond_web.jenisdatailap', verbose_name='Sub Jenis Data ILAP'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tandaterimadata',
            name='id_ilap',
            field=models.ForeignKey(db_column='id_ilap', on_delete=django.db.models.deletion.PROTECT, to='diamond_web.ilap', verbose_name='ILAP'),
        ),
        migrations.AlterField(
            model_name='tandaterimadata',
            name='id_perekam',
            field=models.ForeignKey(db_column='id_perekam', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Perekam'),
        ),
        migrations.AlterField(
            model_name='tiket',
            name='id_durasi_jatuh_tempo_pide',
            field=models.ForeignKey(blank=True, db_column='id_durasi_jatuh_tempo_pide', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='durasi_jatuh_tempo_pide_tikets', to='diamond_web.durasijatuhtempo', verbose_name='Durasi Jatuh Tempo PIDE'),
        ),
        migrations.AlterField(
            model_name='tiket',
            name='id_durasi_jatuh_tempo_pmde',
            field=models.ForeignKey(blank=True, db_column='id_durasi_jatuh_tempo_pmde', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='durasi_jatuh_tempo_pmde_tikets', to='diamond_web.durasijatuhtempo', verbose_name='Durasi Jatuh Tempo PMDE'),
        ),
        migrations.AlterField(
            model_name='tiket',
            name='id_jenis_prioritas_data',
            field=models.ForeignKey(blank=True, db_column='id_jenis_prioritas_data', null=True, on_delete=django.db.models.deletion.PROTECT, to='diamond_web.jenisprioritasdata', verbose_name='Jenis Prioritas Data'),
        ),
        migrations.AlterField(
            model_name='tiket',
            name='id_periode_data',
            field=models.ForeignKey(db_column='id_periode_data', on_delete=django.db.models.deletion.PROTECT, to='diamond_web.periodejenisdata', verbose_name='Periode Jenis Data'),
        ),
        migrations.AlterField(
            model_name='tiketaction',
            name='id_tiket',
            field=models.ForeignKey(db_column='id_tiket', on_delete=django.db.models.deletion.PROTECT, to='diamond_web.tiket', verbose_name='Tiket'),
        ),
        migrations.AlterField(
            model_name='tiketaction',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tiketpic',
            name='id_tiket',
            field=models.ForeignKey(db_column='id_tiket', on_delete=django.db.models.deletion.PROTECT, to='diamond_web.tiket', verbose_name='Tiket'),
        ),
        migrations.AlterField(
            model_name='tiketpic',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
