# Generated by Django 5.2.11 on 2026-02-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diamond_web", "0029_alter_backupdata_id_tiket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backupdata",
            name="nama_file",
            field=models.CharField(default="", max_length=255),
        ),
    ]
