from .kategori_ilap import KategoriILAPForm
from .ilap import ILAPForm
from .jenis_data_ilap import JenisDataILAPForm
from .jenis_tabel import JenisTabelForm
from .jenis_prioritas_data import JenisPrioritasDataForm
from .kategori_wilayah import KategoriWilayahForm
from .klasifikasi_tabel import KlasifikasiTabelForm
from .klasifikasi_jenis_data import KlasifikasiJenisDataForm
from .periode_pengiriman import PeriodePengirimanForm
from .periode_jenis_data import PeriodeJenisDataForm
from .pic import PICForm
from .durasi_jatuh_tempo import DurasiJatuhTempoForm
from .tanda_terima_data import TandaTerimaDataForm
from .nama_tabel import NamaTabelForm
from .tiket import TiketForm