from .kategori_ilap import KategoriILAPForm
from .ilap import ILAPForm
from .jenis_data_ilap import JenisDataILAPForm
from .jenis_tabel import JenisTabelForm
from .kategori_wilayah import KategoriWilayahForm
from .klasifikasi_tabel import KlasifikasiTabelForm
from .klasifikasi_jenis_data import KlasifikasiJenisDataForm
from .periode_pengiriman import PeriodePengirimanForm
from .periode_jenis_data import PeriodeJenisDataForm