# Generated by Django 5.2.10 on 2026-01-29 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diamond_web", "0014_tandaterimadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetilTandaTerima",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "id_tanda_terima",
                    models.ForeignKey(
                        db_column="id_tanda_terima",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detil_items",
                        to="diamond_web.tandaterimadata",
                        verbose_name="Tanda Terima Data",
                    ),
                ),
                (
                    "id_tiket",
                    models.ForeignKey(
                        db_column="id_tiket",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diamond_web.tiket",
                        verbose_name="Tiket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detil Tanda Terima",
                "verbose_name_plural": "Detil Tanda Terima",
                "db_table": "detil_tanda_terima",
                "ordering": ["id"],
                "unique_together": {("id_tanda_terima", "id_tiket")},
            },
        ),
    ]
