# Generated by Django 5.2.10 on 2026-01-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diamond_web", "0015_detiltandaterima"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiket",
            name="nomor_nd_nadine",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nomor ND Nadine"
            ),
        ),
    ]
