# Generated by Django 5.2.10 on 2026-01-30 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0016_tiket_nomor_nd_nadine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi_backup', models.CharField(max_length=255, verbose_name='Lokasi Backup')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Rekam')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_tiket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='diamond_web.tiket', verbose_name='No Tiket')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dilakukan Oleh')),
            ],
            options={
                'db_table': 'backup_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
