# Generated by Django 5.2.10 on 2026-02-06 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0020_consolidate_pic_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picp3de',
            name='id_sub_jenis_data_ilap',
        ),
        migrations.RemoveField(
            model_name='picp3de',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='picpide',
            name='id_sub_jenis_data_ilap',
        ),
        migrations.RemoveField(
            model_name='picpide',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='picpmde',
            name='id_sub_jenis_data_ilap',
        ),
        migrations.RemoveField(
            model_name='picpmde',
            name='id_user',
        ),
        migrations.RenameIndex(
            model_name='pic',
            new_name='pic_tipe_7c24ea_idx',
            old_name='pic_tipe_id_sub_idx',
        ),
        migrations.AlterField(
            model_name='tiket',
            name='id_durasi_jatuh_tempo_pide',
            field=models.ForeignKey(blank=True, db_column='id_durasi_jatuh_tempo_pide', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='durasi_jatuh_tempo_pide_tikets', to='diamond_web.durasijatuhtempo', verbose_name='Durasi Jatuh Tempo PIDE'),
        ),
        migrations.AlterField(
            model_name='tiket',
            name='id_durasi_jatuh_tempo_pmde',
            field=models.ForeignKey(blank=True, db_column='id_durasi_jatuh_tempo_pmde', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='durasi_jatuh_tempo_pmde_tikets', to='diamond_web.durasijatuhtempo', verbose_name='Durasi Jatuh Tempo PMDE'),
        ),
        migrations.DeleteModel(
            name='PICP3DE',
        ),
        migrations.DeleteModel(
            name='PICPIDE',
        ),
        migrations.DeleteModel(
            name='PICPMDE',
        ),
    ]
