# Generated by Django 5.2.10 on 2026-02-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0021_remove_picp3de_id_sub_jenis_data_ilap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tandaterimadata',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
