# Generated by Django 5.2.10 on 2026-02-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0023_alter_detiltandaterima_id_tiket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiketpic',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
