# Generated by Django 5.2.12 on 2026-04-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0032_rename_deskripsi_periodepengiriman_periode_penyampaian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tandaterimadata',
            name='deskripsi',
        ),
        migrations.AlterField(
            model_name='periodepengiriman',
            name='periode_penyampaian',
            field=models.CharField(max_length=50, unique=True, verbose_name='Periode Penyampaian'),
        ),
    ]
