# Generated by Django 5.2.12 on 2026-04-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0033_remove_tandaterimadata_deskripsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiket',
            name='bentuk_data',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bentuk Data'),
        ),
        migrations.AddField(
            model_name='tiket',
            name='cara_penyampaian',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cara Penyampaian'),
        ),
        migrations.AddField(
            model_name='tiket',
            name='nama_pengirim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nama Pengirim'),
        ),
        migrations.AddField(
            model_name='tiket',
            name='nomor_surat_pengantar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomor Surat Pengantar'),
        ),
        migrations.AddField(
            model_name='tiket',
            name='tanggal_surat_pengantar',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Surat Pengantar'),
        ),
    ]
