# Generated by Django 5.2.12 on 2026-04-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0034_tiket_bentuk_data_tiket_cara_penyampaian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupdata',
            name='media_backup',
            field=models.IntegerField(blank=True, null=True, verbose_name='Media Backup'),
        ),
        migrations.AddField(
            model_name='backupdata',
            name='nama_file',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama File'),
        ),
    ]
