# Generated by Django 5.2.12 on 2026-04-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0045_seed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiket',
            name='alasan_ketidaktersediaan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alasan Ketidaktersediaan'),
        ),
        migrations.AddField(
            model_name='tiket',
            name='status_ketersediaan_data',
            field=models.BooleanField(default=True, verbose_name='Status Ketersediaan Data'),
        ),
    ]
